### ISSUE TITLE
Missing proper citation/acknowledgement

### ISSUE THREAD

**Issue by eduardzamfir** [zhoushen1/MEASNet#2]
Hi,

I came across your work and found it quite interesting. 

However, I noticed that portions of your code, especially [here](https://github.com/zhoushen1/MEASNet/blob/0e6e8a8b1bd03112bc6bbe574bec5c38b7bc200a/MEASNet/net/FD_MEE.py#L49), appear to be taken from our recent [ICML 2024 "See More Details: Efficient Image Super-Resolution by Experts Mining"](https://arxiv.org/abs/2402.03412), but they lack proper citation or acknowledgement. Could you please address this?

Thank you.

**Comment by zhoushen1** [comment]
"See More Details: Efficient Image Super Solution by Experts" Mining is a fantastic job! We will cite this excellent work during the revision phase! thank you!



---- Replied Message ----
| From | Eduard ***@***.***> |
| Date | 09/19/2024 21:51 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [zhoushen1/MEASNet] Missing proper citation/acknowledgement (Issue #2) |

Hi,

I came across your work and found it quite interesting.

However, I noticed that portions of your code, especially here, appear to be taken from our recent ICML 2024 "See More Details: Efficient Image Super-Resolution by Experts Mining", but they lack proper citation or acknowledgement. Could you please address this?

Thank you.

**Comment by zhoushen1** [comment]
Your job is an amazing one, and we have been greatly inspired by it! I would like to express my gratitude to you. We will correctly cite and confirm the relevant sections.

**Comment by zhoushen1** [comment]
> 嗨，
> 
> 我偶然发现了你的作品，发现它很有趣。
> 
> 但是,我注意到,您的代码的某些部分,特别是[这里](https://github.com/zhoushen1/MEASNet/blob/0e6e8a8b1bd03112bc6bbe574bec5c38b7bc200a/MEASNet/net/FD_MEE.py#L49),似乎取自我们最近的[ ICML 2024 “查看更多细节:专家挖掘的高效图像超分辨率”。](https://arxiv.org/abs/2402.03412)但是,它们缺乏适当的引用或确认。 你能解决这个问题吗？
> 
> 谢谢。

Your job is an amazing one, and we have been greatly inspired by it! I would like to express my gratitude to you. We will correctly cite and confirm the relevant sections.

**Comment by zhoushen1** [comment]
> Hi,
> 
> I came across your work and found it quite interesting.
> 
> However, I noticed that portions of your code, especially [here](https://github.com/zhoushen1/MEASNet/blob/0e6e8a8b1bd03112bc6bbe574bec5c38b7bc200a/MEASNet/net/FD_MEE.py#L49), appear to be taken from our recent [ICML 2024 "See More Details: Efficient Image Super-Resolution by Experts Mining"](https://arxiv.org/abs/2402.03412), but they lack proper citation or acknowledgement. Could you please address this?
> 
> Thank you.

Your job is an amazing one, and we have been greatly inspired by it! I would like to express my gratitude to you. We will correctly cite and confirm the relevant sections.
